name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
  DeployToDev:
    name: Deploy to dev
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: [build]
    environment: 
      name: dev
      url: 'http://dev.myapp.com'    
    steps:
    - name: executing deploying
      run: echo I am deploying to dev
  DeployToStaging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: github.event.ref == 'refs/heads/master'
    needs: [build]
    environment: 
      name: staging
      url: 'http://staging.myapp.com'    
    steps:
    - name: staging deployment script
      run: echo I am staging server
  DeployToProd:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [DeployToStaging]
    environment: 
      name: prod
      url: 'http://myapp.com'    
    steps:
    - name: Prod deployment script
      run: echo I am on production server
